# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aaa5685eae7949a1311476f3a9ab51650604927b4c274f6d220b2633882ca06ac15bfb46f6c5f9825d125f0f88b6001466e22519f27e6510ba3f2fd9b165db71

test:
  secret_key_base: 25b652bd47a92d75f61a5877b6b58efd557fce9fcc73bc73915ef44b85063165843229b6c42f884173c4468fcec4388ba8b5f34e4a484ed5686d15586a3b30ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
